<a href="https://colab.research.google.com/github/SyedMisbahGit/FirstGitHubRepo/blob/main/feedforwarding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
np.random.seed(42)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

X = np.random.randint(1, 5, (2, 2))

W1 = np.random.randint(1, 5, (2, 2))
b1 = np.random.randint(1, 5, (1, 2))

W2 = np.random.randint(1, 5, (2, 2))
b2 = np.random.randint(1, 5, (1, 2))

W3 = np.random.randint(1, 5, (2, 1))
b3 = np.random.randint(1, 5, (1, 1))

H1 = sigmoid(np.dot(X, W1) + b1)
H2 = sigmoid(np.dot(H1, W2) + b2)
Y = sigmoid(np.dot(H2, W3) + b3)

print("X:\n", X)
print("\nH1:\n", H1)
print("\nH2:\n", H2)
print("\nY:\n", Y)

X:
 [[3 4]
 [1 3]]

H1:
 [[0.99999989 0.99999998]
 [0.99987661 0.99987661]]

H2:
 [[0.9999546  0.99908895]
 [0.99995457 0.99908827]]

Y:
 [[0.99999383]
 [0.99999383]]


In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

tf.random.set_seed(42)
model = Sequential([
    Dense(2, activation='relu', input_shape=(2,)),
    Dense(2, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

output = model.predict(X)

print("X:\n", X)
print("\nY:\n", output)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step
X:
 [[3 4]
 [1 3]]

Y:
 [[0.6485976 ]
 [0.64543074]]
